apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: accuweatherapi
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: accuweatherapi
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/csharp-weatherforecast
      ref:
        branch: main
